version: '3'

services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    environment: 
      - MONGO_URI=mongodb://mongodb:27017

  mongodb:
    build:
      context: .
      dockerfile: Dockerfile.mongo
    ports:
      - "27017:27017"
